# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: drsinBlog 
email: 86478582@qq.com
description: > # this means to ignore newlines until "baseurl:"
  我不生产代码，只是github的搬用工   
show_downloads: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ninowon.com" # the base hostname & protocol for your site
github_username: drsin 

# Build settings
markdown: kramdown
kramdown:
input: GFM
syntax_highlighter: rouge
category_dir: category
tag_dir: tag/
excerpt_separator: "\n\n\n\n"
gems: [jekyll-paginate]
paginate: 6
baidu_tongji_id: 9509c46947d444c42bdfd33deeaff852
theme: jekyll-theme-cayman
gems: [jekyll-test-plugin, jekyll-jsonify, jekyll-assets]
#this wile require each of these gems automatically
